<?xml version = "1.0" ?>
<?xml-stylesheet type="text/xsl" href="SystemBOM.xsl"?>
<!DOCTYPE GRID [
  <!ELEMENT GRID (BANDS, COLUMNS, ROWS*)>
  <!ATTLIST GRID ExportVersion CDATA #REQUIRED>
  <!ELEMENT BANDS (BAND*)>
  <!ELEMENT BAND EMPTY>
  <!ATTLIST BAND Index CDATA #REQUIRED>
  <!ATTLIST BAND Caption CDATA #IMPLIED>
  <!ELEMENT COLUMNS (COLUMN*)>
  <!ELEMENT COLUMN EMPTY>
  <!ATTLIST COLUMN Name CDATA #REQUIRED>
  <!ATTLIST COLUMN Caption CDATA #IMPLIED>
  <!ATTLIST COLUMN Index CDATA #REQUIRED>
  <!ATTLIST COLUMN BandIndex CDATA #REQUIRED>
  <!ATTLIST COLUMN RowIndex CDATA #REQUIRED>
  <!ATTLIST COLUMN ColIndex CDATA #REQUIRED>
  <!ATTLIST COLUMN Width CDATA #IMPLIED>
  <!ELEMENT GROUP (GROUP*, ROW*)>
  <!ATTLIST GROUP GroupText CDATA #IMPLIED>
  <!ELEMENT ROWS (ROW*)>
  <!ELEMENT ROW EMPTY>
  <!ATTLIST ROW Address1 CDATA #IMPLIED>
  <!ATTLIST ROW Address2 CDATA #IMPLIED>
  <!ATTLIST ROW Address3 CDATA #IMPLIED>
  <!ATTLIST ROW Address4 CDATA #IMPLIED>
  <!ATTLIST ROW Application_BuildNumber CDATA #IMPLIED>
  <!ATTLIST ROW ApprovedBy CDATA #IMPLIED>
  <!ATTLIST ROW Author CDATA #IMPLIED>
  <!ATTLIST ROW CheckedBy CDATA #IMPLIED>
  <!ATTLIST ROW ClassName CDATA #IMPLIED>
  <!ATTLIST ROW Code_IEC CDATA #IMPLIED>
  <!ATTLIST ROW Code_JEITA CDATA #IMPLIED>
  <!ATTLIST ROW Comment CDATA #IMPLIED>
  <!ATTLIST ROW CompanyName CDATA #IMPLIED>
  <!ATTLIST ROW Component_Kind CDATA #IMPLIED>
  <!ATTLIST ROW ComponentKind CDATA #IMPLIED>
  <!ATTLIST ROW CurrentDate CDATA #IMPLIED>
  <!ATTLIST ROW CurrentTime CDATA #IMPLIED>
  <!ATTLIST ROW Date CDATA #IMPLIED>
  <!ATTLIST ROW Description CDATA #IMPLIED>
  <!ATTLIST ROW Designator CDATA #IMPLIED>
  <!ATTLIST ROW Designator_X_Mil_ CDATA #IMPLIED>
  <!ATTLIST ROW Designator_X_mm_ CDATA #IMPLIED>
  <!ATTLIST ROW Designator_Y_Mil_ CDATA #IMPLIED>
  <!ATTLIST ROW Designator_Y_mm_ CDATA #IMPLIED>
  <!ATTLIST ROW DesignItemId CDATA #IMPLIED>
  <!ATTLIST ROW Document CDATA #IMPLIED>
  <!ATTLIST ROW DocumentFullPathAndName CDATA #IMPLIED>
  <!ATTLIST ROW DocumentName CDATA #IMPLIED>
  <!ATTLIST ROW DocumentNumber CDATA #IMPLIED>
  <!ATTLIST ROW DrawnBy CDATA #IMPLIED>
  <!ATTLIST ROW Engineer CDATA #IMPLIED>
  <!ATTLIST ROW Footprint CDATA #IMPLIED>
  <!ATTLIST ROW Height_Mil_ CDATA #IMPLIED>
  <!ATTLIST ROW Height_mm_ CDATA #IMPLIED>
  <!ATTLIST ROW Ibis_Model CDATA #IMPLIED>
  <!ATTLIST ROW ImagePath CDATA #IMPLIED>
  <!ATTLIST ROW Index CDATA #IMPLIED>
  <!ATTLIST ROW ItemGUID CDATA #IMPLIED>
  <!ATTLIST ROW LatestRevisionDate CDATA #IMPLIED>
  <!ATTLIST ROW LatestRevisionNote CDATA #IMPLIED>
  <!ATTLIST ROW Library_Name CDATA #IMPLIED>
  <!ATTLIST ROW Library_Reference CDATA #IMPLIED>
  <!ATTLIST ROW LibRef CDATA #IMPLIED>
  <!ATTLIST ROW LogicalDesignator CDATA #IMPLIED>
  <!ATTLIST ROW Model_Footprint CDATA #IMPLIED>
  <!ATTLIST ROW Models CDATA #IMPLIED>
  <!ATTLIST ROW ModifiedDate CDATA #IMPLIED>
  <!ATTLIST ROW Organization CDATA #IMPLIED>
  <!ATTLIST ROW PackageDescription CDATA #IMPLIED>
  <!ATTLIST ROW PackageReference CDATA #IMPLIED>
  <!ATTLIST ROW PartType CDATA #IMPLIED>
  <!ATTLIST ROW PCB3D CDATA #IMPLIED>
  <!ATTLIST ROW PhysicalPath CDATA #IMPLIED>
  <!ATTLIST ROW Pins CDATA #IMPLIED>
  <!ATTLIST ROW Project CDATA #IMPLIED>
  <!ATTLIST ROW ProjectName CDATA #IMPLIED>
  <!ATTLIST ROW Published CDATA #IMPLIED>
  <!ATTLIST ROW Publisher CDATA #IMPLIED>
  <!ATTLIST ROW Quantity CDATA #IMPLIED>
  <!ATTLIST ROW Revision CDATA #IMPLIED>
  <!ATTLIST ROW RevisionGUID CDATA #IMPLIED>
  <!ATTLIST ROW Rule CDATA #IMPLIED>
  <!ATTLIST ROW SheetNumber CDATA #IMPLIED>
  <!ATTLIST ROW SheetTotal CDATA #IMPLIED>
  <!ATTLIST ROW Signal_Integrity CDATA #IMPLIED>
  <!ATTLIST ROW Simulation CDATA #IMPLIED>
  <!ATTLIST ROW SourceLibraryName CDATA #IMPLIED>
  <!ATTLIST ROW Sub_Parts CDATA #IMPLIED>
  <!ATTLIST ROW Time CDATA #IMPLIED>
  <!ATTLIST ROW Title CDATA #IMPLIED>
  <!ATTLIST ROW UniqueIdName CDATA #IMPLIED>
  <!ATTLIST ROW UniqueIdPath CDATA #IMPLIED>
  <!ATTLIST ROW Value CDATA #IMPLIED>
  <!ATTLIST ROW Variant CDATA #IMPLIED>
  <!ATTLIST ROW VaultGUID CDATA #IMPLIED>
  <!ATTLIST ROW _ CDATA #IMPLIED>
  <!ATTLIST ROW _ID_ CDATA #IMPLIED>
  <!ATTLIST ROW _PARENTID_ CDATA #IMPLIED>
]>
<GRID ExportVersion="1.0">
  <BANDS>
    <BAND Index="0" Caption=""></BAND>
  </BANDS>
  <COLUMNS>
    <COLUMN Name="Address1" Caption="Address1" Index="0" BandIndex="0" RowIndex="0" ColIndex="0" Width="100"></COLUMN>
    <COLUMN Name="Address2" Caption="Address2" Index="1" BandIndex="0" RowIndex="0" ColIndex="1" Width="100"></COLUMN>
    <COLUMN Name="Address3" Caption="Address3" Index="2" BandIndex="0" RowIndex="0" ColIndex="2" Width="100"></COLUMN>
    <COLUMN Name="Address4" Caption="Address4" Index="3" BandIndex="0" RowIndex="0" ColIndex="3" Width="100"></COLUMN>
    <COLUMN Name="Application_BuildNumber" Caption="Application_BuildNumber" Index="4" BandIndex="0" RowIndex="0" ColIndex="4" Width="100"></COLUMN>
    <COLUMN Name="ApprovedBy" Caption="ApprovedBy" Index="5" BandIndex="0" RowIndex="0" ColIndex="5" Width="100"></COLUMN>
    <COLUMN Name="Author" Caption="Author" Index="6" BandIndex="0" RowIndex="0" ColIndex="6" Width="100"></COLUMN>
    <COLUMN Name="CheckedBy" Caption="CheckedBy" Index="7" BandIndex="0" RowIndex="0" ColIndex="7" Width="100"></COLUMN>
    <COLUMN Name="ClassName" Caption="ClassName" Index="8" BandIndex="0" RowIndex="0" ColIndex="8" Width="100"></COLUMN>
    <COLUMN Name="Code_IEC" Caption="Code_IEC" Index="9" BandIndex="0" RowIndex="0" ColIndex="9" Width="100"></COLUMN>
    <COLUMN Name="Code_JEITA" Caption="Code_JEITA" Index="10" BandIndex="0" RowIndex="0" ColIndex="10" Width="100"></COLUMN>
    <COLUMN Name="Comment" Caption="Comment" Index="11" BandIndex="0" RowIndex="0" ColIndex="11" Width="100"></COLUMN>
    <COLUMN Name="CompanyName" Caption="CompanyName" Index="12" BandIndex="0" RowIndex="0" ColIndex="12" Width="100"></COLUMN>
    <COLUMN Name="Component_Kind" Caption="Component Kind" Index="13" BandIndex="0" RowIndex="0" ColIndex="13" Width="100"></COLUMN>
    <COLUMN Name="ComponentKind" Caption="ComponentKind" Index="14" BandIndex="0" RowIndex="0" ColIndex="14" Width="100"></COLUMN>
    <COLUMN Name="CurrentDate" Caption="CurrentDate" Index="15" BandIndex="0" RowIndex="0" ColIndex="15" Width="100"></COLUMN>
    <COLUMN Name="CurrentTime" Caption="CurrentTime" Index="16" BandIndex="0" RowIndex="0" ColIndex="16" Width="100"></COLUMN>
    <COLUMN Name="Date" Caption="Date" Index="17" BandIndex="0" RowIndex="0" ColIndex="17" Width="100"></COLUMN>
    <COLUMN Name="Description" Caption="Description" Index="18" BandIndex="0" RowIndex="0" ColIndex="18" Width="100"></COLUMN>
    <COLUMN Name="Designator" Caption="Designator" Index="19" BandIndex="0" RowIndex="0" ColIndex="19" Width="100"></COLUMN>
    <COLUMN Name="Designator_X_Mil_" Caption="Designator-X&#40;Mil&#41;" Index="20" BandIndex="0" RowIndex="0" ColIndex="20" Width="100"></COLUMN>
    <COLUMN Name="Designator_X_mm_" Caption="Designator-X&#40;mm&#41;" Index="21" BandIndex="0" RowIndex="0" ColIndex="21" Width="100"></COLUMN>
    <COLUMN Name="Designator_Y_Mil_" Caption="Designator-Y&#40;Mil&#41;" Index="22" BandIndex="0" RowIndex="0" ColIndex="22" Width="100"></COLUMN>
    <COLUMN Name="Designator_Y_mm_" Caption="Designator-Y&#40;mm&#41;" Index="23" BandIndex="0" RowIndex="0" ColIndex="23" Width="100"></COLUMN>
    <COLUMN Name="DesignItemId" Caption="DesignItemId" Index="24" BandIndex="0" RowIndex="0" ColIndex="24" Width="100"></COLUMN>
    <COLUMN Name="Document" Caption="Document" Index="25" BandIndex="0" RowIndex="0" ColIndex="25" Width="100"></COLUMN>
    <COLUMN Name="DocumentFullPathAndName" Caption="DocumentFullPathAndName" Index="26" BandIndex="0" RowIndex="0" ColIndex="26" Width="100"></COLUMN>
    <COLUMN Name="DocumentName" Caption="DocumentName" Index="27" BandIndex="0" RowIndex="0" ColIndex="27" Width="100"></COLUMN>
    <COLUMN Name="DocumentNumber" Caption="DocumentNumber" Index="28" BandIndex="0" RowIndex="0" ColIndex="28" Width="100"></COLUMN>
    <COLUMN Name="DrawnBy" Caption="DrawnBy" Index="29" BandIndex="0" RowIndex="0" ColIndex="29" Width="100"></COLUMN>
    <COLUMN Name="Engineer" Caption="Engineer" Index="30" BandIndex="0" RowIndex="0" ColIndex="30" Width="100"></COLUMN>
    <COLUMN Name="Footprint" Caption="Footprint" Index="31" BandIndex="0" RowIndex="0" ColIndex="31" Width="100"></COLUMN>
    <COLUMN Name="Height_Mil_" Caption="Height&#40;Mil&#41;" Index="32" BandIndex="0" RowIndex="0" ColIndex="32" Width="100"></COLUMN>
    <COLUMN Name="Height_mm_" Caption="Height&#40;mm&#41;" Index="33" BandIndex="0" RowIndex="0" ColIndex="33" Width="100"></COLUMN>
    <COLUMN Name="Ibis_Model" Caption="Ibis Model" Index="34" BandIndex="0" RowIndex="0" ColIndex="34" Width="100"></COLUMN>
    <COLUMN Name="ImagePath" Caption="ImagePath" Index="35" BandIndex="0" RowIndex="0" ColIndex="35" Width="100"></COLUMN>
    <COLUMN Name="Index" Caption="Index" Index="36" BandIndex="0" RowIndex="0" ColIndex="36" Width="100"></COLUMN>
    <COLUMN Name="ItemGUID" Caption="ItemGUID" Index="37" BandIndex="0" RowIndex="0" ColIndex="37" Width="100"></COLUMN>
    <COLUMN Name="LatestRevisionDate" Caption="LatestRevisionDate" Index="38" BandIndex="0" RowIndex="0" ColIndex="38" Width="100"></COLUMN>
    <COLUMN Name="LatestRevisionNote" Caption="LatestRevisionNote" Index="39" BandIndex="0" RowIndex="0" ColIndex="39" Width="100"></COLUMN>
    <COLUMN Name="Library_Name" Caption="Library Name" Index="40" BandIndex="0" RowIndex="0" ColIndex="40" Width="100"></COLUMN>
    <COLUMN Name="Library_Reference" Caption="Library Reference" Index="41" BandIndex="0" RowIndex="0" ColIndex="41" Width="100"></COLUMN>
    <COLUMN Name="LibRef" Caption="LibRef" Index="42" BandIndex="0" RowIndex="0" ColIndex="42" Width="100"></COLUMN>
    <COLUMN Name="LogicalDesignator" Caption="LogicalDesignator" Index="43" BandIndex="0" RowIndex="0" ColIndex="43" Width="100"></COLUMN>
    <COLUMN Name="Model_Footprint" Caption="Model:Footprint" Index="44" BandIndex="0" RowIndex="0" ColIndex="44" Width="100"></COLUMN>
    <COLUMN Name="Models" Caption="Models" Index="45" BandIndex="0" RowIndex="0" ColIndex="45" Width="100"></COLUMN>
    <COLUMN Name="ModifiedDate" Caption="ModifiedDate" Index="46" BandIndex="0" RowIndex="0" ColIndex="46" Width="100"></COLUMN>
    <COLUMN Name="Organization" Caption="Organization" Index="47" BandIndex="0" RowIndex="0" ColIndex="47" Width="100"></COLUMN>
    <COLUMN Name="PackageDescription" Caption="PackageDescription" Index="48" BandIndex="0" RowIndex="0" ColIndex="48" Width="100"></COLUMN>
    <COLUMN Name="PackageReference" Caption="PackageReference" Index="49" BandIndex="0" RowIndex="0" ColIndex="49" Width="100"></COLUMN>
    <COLUMN Name="PartType" Caption="PartType" Index="50" BandIndex="0" RowIndex="0" ColIndex="50" Width="100"></COLUMN>
    <COLUMN Name="PCB3D" Caption="PCB3D" Index="51" BandIndex="0" RowIndex="0" ColIndex="51" Width="100"></COLUMN>
    <COLUMN Name="PhysicalPath" Caption="PhysicalPath" Index="52" BandIndex="0" RowIndex="0" ColIndex="52" Width="100"></COLUMN>
    <COLUMN Name="Pins" Caption="Pins" Index="53" BandIndex="0" RowIndex="0" ColIndex="53" Width="100"></COLUMN>
    <COLUMN Name="Project" Caption="Project" Index="54" BandIndex="0" RowIndex="0" ColIndex="54" Width="100"></COLUMN>
    <COLUMN Name="ProjectName" Caption="ProjectName" Index="55" BandIndex="0" RowIndex="0" ColIndex="55" Width="100"></COLUMN>
    <COLUMN Name="Published" Caption="Published" Index="56" BandIndex="0" RowIndex="0" ColIndex="56" Width="100"></COLUMN>
    <COLUMN Name="Publisher" Caption="Publisher" Index="57" BandIndex="0" RowIndex="0" ColIndex="57" Width="100"></COLUMN>
    <COLUMN Name="Quantity" Caption="Quantity" Index="58" BandIndex="0" RowIndex="0" ColIndex="58" Width="100"></COLUMN>
    <COLUMN Name="Revision" Caption="Revision" Index="59" BandIndex="0" RowIndex="0" ColIndex="59" Width="100"></COLUMN>
    <COLUMN Name="RevisionGUID" Caption="RevisionGUID" Index="60" BandIndex="0" RowIndex="0" ColIndex="60" Width="100"></COLUMN>
    <COLUMN Name="Rule" Caption="Rule" Index="61" BandIndex="0" RowIndex="0" ColIndex="61" Width="100"></COLUMN>
    <COLUMN Name="SheetNumber" Caption="SheetNumber" Index="62" BandIndex="0" RowIndex="0" ColIndex="62" Width="100"></COLUMN>
    <COLUMN Name="SheetTotal" Caption="SheetTotal" Index="63" BandIndex="0" RowIndex="0" ColIndex="63" Width="100"></COLUMN>
    <COLUMN Name="Signal_Integrity" Caption="Signal Integrity" Index="64" BandIndex="0" RowIndex="0" ColIndex="64" Width="100"></COLUMN>
    <COLUMN Name="Simulation" Caption="Simulation" Index="65" BandIndex="0" RowIndex="0" ColIndex="65" Width="100"></COLUMN>
    <COLUMN Name="SourceLibraryName" Caption="SourceLibraryName" Index="66" BandIndex="0" RowIndex="0" ColIndex="66" Width="100"></COLUMN>
    <COLUMN Name="Sub_Parts" Caption="Sub-Parts" Index="67" BandIndex="0" RowIndex="0" ColIndex="67" Width="100"></COLUMN>
    <COLUMN Name="Time" Caption="Time" Index="68" BandIndex="0" RowIndex="0" ColIndex="68" Width="100"></COLUMN>
    <COLUMN Name="Title" Caption="Title" Index="69" BandIndex="0" RowIndex="0" ColIndex="69" Width="100"></COLUMN>
    <COLUMN Name="UniqueIdName" Caption="UniqueIdName" Index="70" BandIndex="0" RowIndex="0" ColIndex="70" Width="100"></COLUMN>
    <COLUMN Name="UniqueIdPath" Caption="UniqueIdPath" Index="71" BandIndex="0" RowIndex="0" ColIndex="71" Width="100"></COLUMN>
    <COLUMN Name="Value" Caption="Value" Index="72" BandIndex="0" RowIndex="0" ColIndex="72" Width="100"></COLUMN>
    <COLUMN Name="Variant" Caption="Variant" Index="73" BandIndex="0" RowIndex="0" ColIndex="73" Width="100"></COLUMN>
    <COLUMN Name="VaultGUID" Caption="VaultGUID" Index="74" BandIndex="0" RowIndex="0" ColIndex="74" Width="100"></COLUMN>
    <COLUMN Name="_" Caption="&#35;" Index="75" BandIndex="0" RowIndex="0" ColIndex="75" Width="100"></COLUMN>
    <COLUMN Name="_ID_" Caption="&#37;ID&#37;" Index="76" BandIndex="0" RowIndex="0" ColIndex="76" Width="100"></COLUMN>
    <COLUMN Name="_PARENTID_" Caption="&#37;PARENTID&#37;" Index="77" BandIndex="0" RowIndex="0" ColIndex="77" Width="100"></COLUMN>
  </COLUMNS>
  <ROWS>
    <ROW Address1="" Address2="" Address3="" Address4="" Application_BuildNumber="" ApprovedBy="" Author="" CheckedBy="" ClassName="caps" Code_IEC="" Code_JEITA="" Comment="470uF" CompanyName="" Component_Kind="Standard" ComponentKind="0" CurrentDate="01/12/2019" CurrentTime="17:25:33" Date="" Description="Capacitor" Designator="C2" Designator_X_Mil_="2755.9" Designator_X_mm_="70" Designator_Y_Mil_="5354.32" Designator_Y_mm_="136" DesignItemId="E CAP" Document="C:&#92;Dev&#92;wifi-lights&#92;pcbs&#92;buck3&#92;buck3.SchDoc" DocumentFullPathAndName="C:&#92;Dev&#92;wifi-lights&#92;pcbs&#92;buck3&#92;buck3.SchDoc" DocumentName="buck3.SchDoc" DocumentNumber="" DrawnBy="" Engineer="" Footprint="CAPAE10083X104N" Height_Mil_="0" Height_mm_="0" Ibis_Model="" ImagePath="" Index="1" ItemGUID="" LatestRevisionDate="" LatestRevisionNote="" Library_Name="buck3.SchLib" Library_Reference="E CAP" LibRef="E CAP" LogicalDesignator="C2" Model_Footprint="" Models="3" ModifiedDate="25/11/2019" Organization="" PackageDescription="" PackageReference="" PartType="470uF" PCB3D="" PhysicalPath="buck3" Pins="2" Project="C:&#92;Dev&#92;wifi-lights&#92;pcbs&#92;buck3&#92;buck3.PrjPcb" ProjectName="buck3.PrjPcb" Published="" Publisher="" Quantity="1" Revision="" RevisionGUID="" Rule="" SheetNumber="" SheetTotal="1" Signal_Integrity="" Simulation="" SourceLibraryName="buck3.SchLib" Sub_Parts="1" Time="" Title="Buck3" UniqueIdName="AUEXIPSH" UniqueIdPath="" Value="470uF" Variant="" VaultGUID="" _="1" _ID_="1092902240" _PARENTID_=""></ROW>
    <ROW Address1="" Address2="" Address3="" Address4="" Application_BuildNumber="" ApprovedBy="" Author="" CheckedBy="" ClassName="" Code_IEC="" Code_JEITA="" Comment="180pF" CompanyName="" Component_Kind="Standard" ComponentKind="0" CurrentDate="01/12/2019" CurrentTime="17:25:33" Date="" Description="Capacitor" Designator="C3" Designator_X_Mil_="3228.34" Designator_X_mm_="82" Designator_Y_Mil_="3484.245" Designator_Y_mm_="88.5" DesignItemId="Cap" Document="C:&#92;Dev&#92;wifi-lights&#92;pcbs&#92;buck3&#92;buck3.SchDoc" DocumentFullPathAndName="C:&#92;Dev&#92;wifi-lights&#92;pcbs&#92;buck3&#92;buck3.SchDoc" DocumentName="buck3.SchDoc" DocumentNumber="" DrawnBy="" Engineer="" Footprint="CAPC 0603 1608X05L" Height_Mil_="0" Height_mm_="0" Ibis_Model="" ImagePath="" Index="2" ItemGUID="" LatestRevisionDate="17-Jul-2002" LatestRevisionNote="Re-released for DXP Platform." Library_Name="buck3.SchLib" Library_Reference="Cap" LibRef="Cap" LogicalDesignator="C3" Model_Footprint="" Models="3" ModifiedDate="25/11/2019" Organization="" PackageDescription="Radial Cap, Thru-Hole; 2 Leads; 0.3 in Pin Spacing" PackageReference="RAD-0.3" PartType="180pF" PCB3D="" PhysicalPath="buck3" Pins="2" Project="C:&#92;Dev&#92;wifi-lights&#92;pcbs&#92;buck3&#92;buck3.PrjPcb" ProjectName="buck3.PrjPcb" Published="8-Jun-2000" Publisher="Altium Limited" Quantity="1" Revision="" RevisionGUID="" Rule="" SheetNumber="" SheetTotal="1" Signal_Integrity="" Simulation="" SourceLibraryName="buck3.SchLib" Sub_Parts="1" Time="" Title="Buck3" UniqueIdName="BBOIIDSP" UniqueIdPath="" Value="180pF" Variant="" VaultGUID="" _="2" _ID_="1092875360" _PARENTID_=""></ROW>
    <ROW Address1="" Address2="" Address3="" Address4="" Application_BuildNumber="" ApprovedBy="" Author="" CheckedBy="" ClassName="" Code_IEC="" Code_JEITA="" Comment="100nF" CompanyName="" Component_Kind="Standard" ComponentKind="0" CurrentDate="01/12/2019" CurrentTime="17:25:33" Date="" Description="Capacitor" Designator="C4" Designator_X_Mil_="3484.245" Designator_X_mm_="88.5" Designator_Y_Mil_="4448.81" Designator_Y_mm_="113" DesignItemId="Cap" Document="C:&#92;Dev&#92;wifi-lights&#92;pcbs&#92;buck3&#92;buck3.SchDoc" DocumentFullPathAndName="C:&#92;Dev&#92;wifi-lights&#92;pcbs&#92;buck3&#92;buck3.SchDoc" DocumentName="buck3.SchDoc" DocumentNumber="" DrawnBy="" Engineer="" Footprint="CAPC 0603 1608X05L" Height_Mil_="0" Height_mm_="0" Ibis_Model="" ImagePath="" Index="3" ItemGUID="" LatestRevisionDate="17-Jul-2002" LatestRevisionNote="Re-released for DXP Platform." Library_Name="buck3.SchLib" Library_Reference="Cap" LibRef="Cap" LogicalDesignator="C4" Model_Footprint="" Models="3" ModifiedDate="25/11/2019" Organization="" PackageDescription="Radial Cap, Thru-Hole; 2 Leads; 0.3 in Pin Spacing" PackageReference="RAD-0.3" PartType="100nF" PCB3D="" PhysicalPath="buck3" Pins="2" Project="C:&#92;Dev&#92;wifi-lights&#92;pcbs&#92;buck3&#92;buck3.PrjPcb" ProjectName="buck3.PrjPcb" Published="8-Jun-2000" Publisher="Altium Limited" Quantity="1" Revision="" RevisionGUID="" Rule="" SheetNumber="" SheetTotal="1" Signal_Integrity="" Simulation="" SourceLibraryName="buck3.SchLib" Sub_Parts="1" Time="" Title="Buck3" UniqueIdName="YTEJQUAO" UniqueIdPath="" Value="100nF" Variant="" VaultGUID="" _="3" _ID_="1092875552" _PARENTID_=""></ROW>
    <ROW Address1="" Address2="" Address3="" Address4="" Application_BuildNumber="" ApprovedBy="" Author="" CheckedBy="" ClassName="" Code_IEC="" Code_JEITA="" Comment="12pF" CompanyName="" Component_Kind="Standard" ComponentKind="0" CurrentDate="01/12/2019" CurrentTime="17:25:33" Date="" Description="Capacitor" Designator="C5" Designator_X_Mil_="3956.685" Designator_X_mm_="100.5" Designator_Y_Mil_="3267.71" Designator_Y_mm_="83" DesignItemId="Cap" Document="C:&#92;Dev&#92;wifi-lights&#92;pcbs&#92;buck3&#92;buck3.SchDoc" DocumentFullPathAndName="C:&#92;Dev&#92;wifi-lights&#92;pcbs&#92;buck3&#92;buck3.SchDoc" DocumentName="buck3.SchDoc" DocumentNumber="" DrawnBy="" Engineer="" Footprint="CAPC 0603 1608X05L" Height_Mil_="0" Height_mm_="0" Ibis_Model="" ImagePath="" Index="4" ItemGUID="" LatestRevisionDate="17-Jul-2002" LatestRevisionNote="Re-released for DXP Platform." Library_Name="buck3.SchLib" Library_Reference="Cap" LibRef="Cap" LogicalDesignator="C5" Model_Footprint="" Models="3" ModifiedDate="25/11/2019" Organization="" PackageDescription="Radial Cap, Thru-Hole; 2 Leads; 0.3 in Pin Spacing" PackageReference="RAD-0.3" PartType="12pF" PCB3D="" PhysicalPath="buck3" Pins="2" Project="C:&#92;Dev&#92;wifi-lights&#92;pcbs&#92;buck3&#92;buck3.PrjPcb" ProjectName="buck3.PrjPcb" Published="8-Jun-2000" Publisher="Altium Limited" Quantity="1" Revision="" RevisionGUID="" Rule="" SheetNumber="" SheetTotal="1" Signal_Integrity="" Simulation="" SourceLibraryName="buck3.SchLib" Sub_Parts="1" Time="" Title="Buck3" UniqueIdName="PTCYOHRW" UniqueIdPath="" Value="12pF" Variant="" VaultGUID="" _="4" _ID_="1092875456" _PARENTID_=""></ROW>
    <ROW Address1="" Address2="" Address3="" Address4="" Application_BuildNumber="" ApprovedBy="" Author="" CheckedBy="" ClassName="" Code_IEC="" Code_JEITA="" Comment="3.3nF" CompanyName="" Component_Kind="Standard" ComponentKind="0" CurrentDate="01/12/2019" CurrentTime="17:25:33" Date="" Description="Capacitor" Designator="C6" Designator_X_Mil_="4015.74" Designator_X_mm_="102" Designator_Y_Mil_="3956.685" Designator_Y_mm_="100.5" DesignItemId="Cap" Document="C:&#92;Dev&#92;wifi-lights&#92;pcbs&#92;buck3&#92;buck3.SchDoc" DocumentFullPathAndName="C:&#92;Dev&#92;wifi-lights&#92;pcbs&#92;buck3&#92;buck3.SchDoc" DocumentName="buck3.SchDoc" DocumentNumber="" DrawnBy="" Engineer="" Footprint="CAPC 0603 1608X05L" Height_Mil_="0" Height_mm_="0" Ibis_Model="" ImagePath="" Index="5" ItemGUID="" LatestRevisionDate="17-Jul-2002" LatestRevisionNote="Re-released for DXP Platform." Library_Name="buck3.SchLib" Library_Reference="Cap" LibRef="Cap" LogicalDesignator="C6" Model_Footprint="" Models="3" ModifiedDate="25/11/2019" Organization="" PackageDescription="Radial Cap, Thru-Hole; 2 Leads; 0.3 in Pin Spacing" PackageReference="RAD-0.3" PartType="3.3nF" PCB3D="" PhysicalPath="buck3" Pins="2" Project="C:&#92;Dev&#92;wifi-lights&#92;pcbs&#92;buck3&#92;buck3.PrjPcb" ProjectName="buck3.PrjPcb" Published="8-Jun-2000" Publisher="Altium Limited" Quantity="1" Revision="" RevisionGUID="" Rule="" SheetNumber="" SheetTotal="1" Signal_Integrity="" Simulation="" SourceLibraryName="buck3.SchLib" Sub_Parts="1" Time="" Title="Buck3" UniqueIdName="EJTMKPWY" UniqueIdPath="" Value="3.3nF" Variant="" VaultGUID="" _="5" _ID_="1092875072" _PARENTID_=""></ROW>
    <ROW Address1="" Address2="" Address3="" Address4="" Application_BuildNumber="" ApprovedBy="" Author="" CheckedBy="" ClassName="" Code_IEC="" Code_JEITA="" Comment="100nF" CompanyName="" Component_Kind="Standard" ComponentKind="0" CurrentDate="01/12/2019" CurrentTime="17:25:33" Date="" Description="Capacitor" Designator="C7" Designator_X_Mil_="5895.5" Designator_X_mm_="149.746" Designator_Y_Mil_="4734.4" Designator_Y_mm_="120.254" DesignItemId="Cap" Document="C:&#92;Dev&#92;wifi-lights&#92;pcbs&#92;buck3&#92;buck3.SchDoc" DocumentFullPathAndName="C:&#92;Dev&#92;wifi-lights&#92;pcbs&#92;buck3&#92;buck3.SchDoc" DocumentName="buck3.SchDoc" DocumentNumber="" DrawnBy="" Engineer="" Footprint="CAPC 0603 1608X05L" Height_Mil_="0" Height_mm_="0" Ibis_Model="" ImagePath="" Index="6" ItemGUID="" LatestRevisionDate="17-Jul-2002" LatestRevisionNote="Re-released for DXP Platform." Library_Name="buck3.SchLib" Library_Reference="Cap" LibRef="Cap" LogicalDesignator="C7" Model_Footprint="" Models="3" ModifiedDate="25/11/2019" Organization="" PackageDescription="Radial Cap, Thru-Hole; 2 Leads; 0.3 in Pin Spacing" PackageReference="RAD-0.3" PartType="100nF" PCB3D="" PhysicalPath="buck3" Pins="2" Project="C:&#92;Dev&#92;wifi-lights&#92;pcbs&#92;buck3&#92;buck3.PrjPcb" ProjectName="buck3.PrjPcb" Published="8-Jun-2000" Publisher="Altium Limited" Quantity="1" Revision="" RevisionGUID="" Rule="" SheetNumber="" SheetTotal="1" Signal_Integrity="" Simulation="" SourceLibraryName="buck3.SchLib" Sub_Parts="1" Time="" Title="Buck3" UniqueIdName="WYPUTPPM" UniqueIdPath="" Value="100nF" Variant="" VaultGUID="" _="6" _ID_="1092875264" _PARENTID_=""></ROW>
    <ROW Address1="" Address2="" Address3="" Address4="" Application_BuildNumber="" ApprovedBy="" Author="" CheckedBy="" ClassName="" Code_IEC="" Code_JEITA="" Comment="100pF" CompanyName="" Component_Kind="Standard" ComponentKind="0" CurrentDate="01/12/2019" CurrentTime="17:25:33" Date="" Description="Capacitor" Designator="C8" Designator_X_Mil_="6082.665" Designator_X_mm_="154.5" Designator_Y_Mil_="5393.69" Designator_Y_mm_="137" DesignItemId="Cap" Document="C:&#92;Dev&#92;wifi-lights&#92;pcbs&#92;buck3&#92;buck3.SchDoc" DocumentFullPathAndName="C:&#92;Dev&#92;wifi-lights&#92;pcbs&#92;buck3&#92;buck3.SchDoc" DocumentName="buck3.SchDoc" DocumentNumber="" DrawnBy="" Engineer="" Footprint="CAPC 0603 1608X05L" Height_Mil_="0" Height_mm_="0" Ibis_Model="" ImagePath="" Index="7" ItemGUID="" LatestRevisionDate="17-Jul-2002" LatestRevisionNote="Re-released for DXP Platform." Library_Name="buck3.SchLib" Library_Reference="Cap" LibRef="Cap" LogicalDesignator="C8" Model_Footprint="" Models="3" ModifiedDate="25/11/2019" Organization="" PackageDescription="Radial Cap, Thru-Hole; 2 Leads; 0.3 in Pin Spacing" PackageReference="RAD-0.3" PartType="100pF" PCB3D="" PhysicalPath="buck3" Pins="2" Project="C:&#92;Dev&#92;wifi-lights&#92;pcbs&#92;buck3&#92;buck3.PrjPcb" ProjectName="buck3.PrjPcb" Published="8-Jun-2000" Publisher="Altium Limited" Quantity="1" Revision="" RevisionGUID="" Rule="" SheetNumber="" SheetTotal="1" Signal_Integrity="" Simulation="" SourceLibraryName="buck3.SchLib" Sub_Parts="1" Time="" Title="Buck3" UniqueIdName="NGAJSRRD" UniqueIdPath="" Value="100pF" Variant="" VaultGUID="" _="7" _ID_="1092875168" _PARENTID_=""></ROW>
    <ROW Address1="" Address2="" Address3="" Address4="" Application_BuildNumber="" ApprovedBy="" Author="" CheckedBy="" ClassName="" Code_IEC="" Code_JEITA="" Comment="1uF" CompanyName="" Component_Kind="Standard" ComponentKind="0" CurrentDate="01/12/2019" CurrentTime="17:25:33" Date="" Description="Capacitor" Designator="C9" Designator_X_Mil_="6358.255" Designator_X_mm_="161.5" Designator_Y_Mil_="4763.77" Designator_Y_mm_="121" DesignItemId="Cap" Document="C:&#92;Dev&#92;wifi-lights&#92;pcbs&#92;buck3&#92;buck3.SchDoc" DocumentFullPathAndName="C:&#92;Dev&#92;wifi-lights&#92;pcbs&#92;buck3&#92;buck3.SchDoc" DocumentName="buck3.SchDoc" DocumentNumber="" DrawnBy="" Engineer="" Footprint="CAPC 0603 1608X05L" Height_Mil_="0" Height_mm_="0" Ibis_Model="" ImagePath="" Index="8" ItemGUID="" LatestRevisionDate="17-Jul-2002" LatestRevisionNote="Re-released for DXP Platform." Library_Name="buck3.SchLib" Library_Reference="Cap" LibRef="Cap" LogicalDesignator="C9" Model_Footprint="" Models="3" ModifiedDate="25/11/2019" Organization="" PackageDescription="Radial Cap, Thru-Hole; 2 Leads; 0.3 in Pin Spacing" PackageReference="RAD-0.3" PartType="1uF" PCB3D="" PhysicalPath="buck3" Pins="2" Project="C:&#92;Dev&#92;wifi-lights&#92;pcbs&#92;buck3&#92;buck3.PrjPcb" ProjectName="buck3.PrjPcb" Published="8-Jun-2000" Publisher="Altium Limited" Quantity="1" Revision="" RevisionGUID="" Rule="" SheetNumber="" SheetTotal="1" Signal_Integrity="" Simulation="" SourceLibraryName="buck3.SchLib" Sub_Parts="1" Time="" Title="Buck3" UniqueIdName="JFAMGDBG" UniqueIdPath="" Value="1uF" Variant="" VaultGUID="" _="8" _ID_="1092874784" _PARENTID_=""></ROW>
    <ROW Address1="" Address2="" Address3="" Address4="" Application_BuildNumber="" ApprovedBy="" Author="" CheckedBy="" ClassName="" Code_IEC="" Code_JEITA="" Comment="1uF" CompanyName="" Component_Kind="Standard" ComponentKind="0" CurrentDate="01/12/2019" CurrentTime="17:25:33" Date="" Description="Capacitor" Designator="C10" Designator_X_Mil_="6466.68" Designator_X_mm_="164.254" Designator_Y_Mil_="3394.245" Designator_Y_mm_="86.214" DesignItemId="Cap" Document="C:&#92;Dev&#92;wifi-lights&#92;pcbs&#92;buck3&#92;buck3.SchDoc" DocumentFullPathAndName="C:&#92;Dev&#92;wifi-lights&#92;pcbs&#92;buck3&#92;buck3.SchDoc" DocumentName="buck3.SchDoc" DocumentNumber="" DrawnBy="" Engineer="" Footprint="CAPC 0603 1608X05L" Height_Mil_="0" Height_mm_="0" Ibis_Model="" ImagePath="" Index="9" ItemGUID="" LatestRevisionDate="17-Jul-2002" LatestRevisionNote="Re-released for DXP Platform." Library_Name="buck3.SchLib" Library_Reference="Cap" LibRef="Cap" LogicalDesignator="C10" Model_Footprint="" Models="3" ModifiedDate="25/11/2019" Organization="" PackageDescription="Radial Cap, Thru-Hole; 2 Leads; 0.3 in Pin Spacing" PackageReference="RAD-0.3" PartType="1uF" PCB3D="" PhysicalPath="buck3" Pins="2" Project="C:&#92;Dev&#92;wifi-lights&#92;pcbs&#92;buck3&#92;buck3.PrjPcb" ProjectName="buck3.PrjPcb" Published="8-Jun-2000" Publisher="Altium Limited" Quantity="1" Revision="" RevisionGUID="" Rule="" SheetNumber="" SheetTotal="1" Signal_Integrity="" Simulation="" SourceLibraryName="buck3.SchLib" Sub_Parts="1" Time="" Title="Buck3" UniqueIdName="VLDGWTTQ" UniqueIdPath="" Value="1uF" Variant="" VaultGUID="" _="9" _ID_="1092874976" _PARENTID_=""></ROW>